# https://www.jhipster.tech/profiles/
# https://www.jhipster.tech/common-application-properties/
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html


logging:
  level:
    com.github.nossomercadolivre: DEBUG

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:meumercadolivre;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # spring.datasource.url=jdbc:h2:file:/data/demo
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect

server:
  port: 80


jwt:
  expiration: 604800000
  secret: qualquerCoisaAquiNossoMercadoLivre
